### ISSUE TITLE
AttributeError due to numpy.complex

### ISSUE THREAD

**Issue by DavidPost-1** [nkarast/PyNAFF#4]
This line in `pnf.naff()` raises an AttributeError with numpy 1.24.1 because [using the alias np.complex was deprecated in 1.20.0](https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations). Using python's `complex()` method fixes the problem.

https://github.com/nkarast/PyNAFF/blob/6395d5363c9e3eb5255e58397165453e580d163b/PyNAFF/PyNAFF.py#L213

**Comment by oscarxblanco** [comment]
Great,
is this project maintained ?

o

**Comment by DavidPost-1** [comment]
I've spoken to one of the authors, and they've confirmed that this issue is going to be fixed.

**Comment by PZiso** [comment]
Hello,

The new release (1.1.5) that fixed the above issue is now available on https://pypi.org/project/PyNAFF/

The project is still maintained and we planning to optimise PyNAFF further and enhance its capabilities.

For the time being, thank you for using PyNAFF and for sending us your requests/suggestions.
